using System;
using System.Collections.Generic;
using System.Text;
using WpadManager.Core.Model;
using WpadManager.Core.Parser;

namespace WpadManager.Core.Generator
{
    // Deterministically renders a RuleSet back into a valid PAC JavaScript file.
    // Comments round-trip as // lines above each rule; disabled rules are emitted
    // commented-out so they remain visible in the .pac but never fire.
    public static class PacGenerator
    {
        public static string Generate(RuleSet rs)
        {
            Dictionary<int, int> ignore;
            return Generate(rs, out ignore);
        }

        // Same output as Generate, but also reports the 1-based source line on which each
        // rule's statement is emitted (lineToOrder[line] = rule.Order). This lets line-based
        // findings from the security pass be attributed back to the rule the operator sees,
        // so the UI can say "правило N" instead of "строка N".
        public static string Generate(RuleSet rs, out Dictionary<int, int> lineToOrder)
        {
            lineToOrder = new Dictionary<int, int>();

            // Special case: an import that could not find FindProxyForURL is kept whole.
            if (rs.Rules.Count == 0 && rs.Unparsed.Count == 1 &&
                rs.Unparsed[0].Reason == "No FindProxyForURL function")
            {
                return rs.Unparsed[0].RawText;
            }

            // Every piece of stored text below is either JS-escaped (JsString), reduced to a
            // single comment line (LineComment / BlockComment) or checked to be a plain
            // operand (subject / function name). The model can come from a hand-edited
            // .history.json, so nothing in it may be able to change the program's structure.
            StringBuilder sb = new StringBuilder();
            sb.Append("// PAC file generated by WPAD File Manager\n");
            if (!string.IsNullOrEmpty(rs.Name)) sb.Append("// RuleSet: ").Append(LineComment(rs.Name)).Append('\n');
            sb.Append("// Generated: ").Append(Iso.Now()).Append('\n');
            AppendComment(sb, "", rs.HeaderComment);
            sb.Append('\n');

            // Helper functions / top-level code preserved verbatim before the main function.
            for (int i = 0; i < rs.Unparsed.Count; i++)
            {
                UnparsedBlock ub = rs.Unparsed[i];
                if (IsTopLevel(ub))
                {
                    sb.Append("// [preserved from import] ").Append(LineComment(ub.Reason)).Append('\n');
                    sb.Append(ub.RawText).Append('\n').Append('\n');
                }
            }

            sb.Append("function FindProxyForURL(url, host) {\n");

            // Statements the recognizer could not model are emitted where they were in the
            // source — in front of the rule that followed them — since moving one changes
            // which return fires first.
            HashSet<string> ruleIds = new HashSet<string>();
            for (int i = 0; i < rs.Rules.Count; i++) if (rs.Rules[i].Id != null) ruleIds.Add(rs.Rules[i].Id);

            LineCounter lines = new LineCounter();
            for (int i = 0; i < rs.Rules.Count; i++)
            {
                Rule r = rs.Rules[i];
                for (int u = 0; u < rs.Unparsed.Count; u++)
                {
                    UnparsedBlock ub = rs.Unparsed[u];
                    if (IsInBody(ub) && r.Id != null && ub.BeforeRuleId == r.Id) AppendUnparsed(sb, ub);
                }

                string stmt = "if (" + GenCondition(r.Condition) + ") return " + JsString(ActionText.Format(r.Action)) + ";";
                AppendComment(sb, "    ", r.Comment);
                // The rule's statement is emitted on the next line; map it to the rule order.
                lineToOrder[lines.CountUpTo(sb) + 1] = r.Order;
                if (r.Enabled)
                    sb.Append("    ").Append(stmt).Append('\n');
                else
                    sb.Append("    // [disabled] ").Append(LineComment(stmt)).Append('\n');
            }

            // Blocks that came after the last rule (or whose rule no longer exists).
            for (int u = 0; u < rs.Unparsed.Count; u++)
            {
                UnparsedBlock ub = rs.Unparsed[u];
                if (IsInBody(ub) && (ub.BeforeRuleId == null || !ruleIds.Contains(ub.BeforeRuleId))) AppendUnparsed(sb, ub);
            }

            AppendComment(sb, "    ", rs.DefaultComment);
            sb.Append("    return ").Append(JsString(ActionText.Format(rs.DefaultAction))).Append(";\n");

            // Code that followed the default return stays after it, i.e. stays unreachable.
            for (int u = 0; u < rs.Unparsed.Count; u++)
                if (IsAfterDefault(rs.Unparsed[u])) AppendUnparsed(sb, rs.Unparsed[u]);

            sb.Append("}\n");
            return sb.ToString();
        }

        private static bool IsTopLevel(UnparsedBlock ub)
        {
            return ub.Reason != null && ub.Reason.StartsWith("Top-level", StringComparison.Ordinal);
        }

        // Stores written before AfterDefault existed only have the reason text.
        private static bool IsAfterDefault(UnparsedBlock ub)
        {
            return !IsTopLevel(ub) && (ub.AfterDefault ||
                (ub.Reason != null && ub.Reason.StartsWith("Unreachable", StringComparison.Ordinal)));
        }

        private static bool IsInBody(UnparsedBlock ub)
        {
            return !IsTopLevel(ub) && !IsAfterDefault(ub);
        }

        private static void AppendUnparsed(StringBuilder sb, UnparsedBlock ub)
        {
            AppendComment(sb, "    ", ub.Comment);
            sb.Append("    /* unparsed (").Append(BlockComment(ub.Reason)).Append("): */ ")
              .Append(ub.RawText).Append('\n');
        }

        // A (possibly multi-line) comment, one "//" line per line of text.
        private static void AppendComment(StringBuilder sb, string indent, string comment)
        {
            if (string.IsNullOrEmpty(comment)) return;
            string[] parts = comment.Replace("\r\n", "\n").Split('\n', '\r', '\u2028', '\u2029');
            for (int i = 0; i < parts.Length; i++)
            {
                string line = parts[i].Trim();
                if (line.Length > 0) sb.Append(indent).Append("// ").Append(LineComment(line)).Append('\n');
            }
        }

        // Line breaks written so far, counted the way the lexer counts them (CRLF once, lone
        // CR / U+2028 / U+2029 once each — verbatim preserved blocks may contain any of
        // these), so the next line to be written is CountUpTo(sb) + 1. Incremental: only the
        // text appended since the last call is scanned, keeping generation linear.
        private sealed class LineCounter
        {
            private int _scanned;
            private int _lines;

            public int CountUpTo(StringBuilder sb)
            {
                for (; _scanned < sb.Length; _scanned++)
                {
                    char c = sb[_scanned];
                    if (c == '\r')
                    {
                        if (_scanned + 1 >= sb.Length) break;          // decide once the next char is known
                        if (sb[_scanned + 1] == '\n') continue;         // CRLF: counted at the LF
                    }
                    if (Lexer.IsLineTerminator(c)) _lines++;
                }
                return _lines;
            }
        }

        // Text placed after "//": anything JavaScript treats as a line break would end the
        // comment and turn the rest into live code, so flatten it to spaces.
        public static string LineComment(string s)
        {
            if (string.IsNullOrEmpty(s)) return "";
            StringBuilder sb = new StringBuilder(s.Length);
            for (int i = 0; i < s.Length; i++)
                sb.Append(Lexer.IsLineTerminator(s[i]) ? ' ' : s[i]);
            return sb.ToString();
        }

        // Text placed inside /* ... */: must not be able to close the comment early.
        public static string BlockComment(string s)
        {
            if (string.IsNullOrEmpty(s)) return "";
            return s.Replace("*/", "* /");
        }

        // A function name must be a bare identifier; a condition subject must be a single
        // operand (host, url, myIpAddress(), dnsResolve(host), ...). Anything else can only
        // come from a tampered model and is replaced by an inert placeholder — the validator
        // reports it as an error, so such a rule set cannot pass the save gate anyway.
        private static string SafeFn(string fn)
        {
            if (string.IsNullOrEmpty(fn)) return "__invalid_function__";
            for (int i = 0; i < fn.Length; i++)
            {
                char c = fn[i];
                bool ok = (c >= 'a' && c <= 'z') || (c >= 'A' && c <= 'Z') || c == '_' || c == '$' ||
                          (i > 0 && c >= '0' && c <= '9');
                if (!ok) return "__invalid_function__";
            }
            return fn;
        }

        private static string SafeSubject(string subject)
        {
            if (subject == "host" || subject == "url") return subject;   // fast path
            return JsParser.IsSimpleOperand(subject) ? subject : "__invalid_subject__";
        }

        public static string GenCondition(Condition c)
        {
            if (c == null) return "false";
            if (c.Kind == ConditionKind.Single)
            {
                StringBuilder inner = new StringBuilder();
                inner.Append(SafeFn(c.Fn)).Append('(');
                bool first = true;
                if (!string.IsNullOrEmpty(c.Subject))
                {
                    inner.Append(SafeSubject(c.Subject));
                    first = false;
                }
                if (c.Args != null)
                {
                    for (int i = 0; i < c.Args.Count; i++)
                    {
                        if (!first) inner.Append(", ");
                        first = false;
                        inner.Append(JsString(c.Args[i]));
                    }
                }
                inner.Append(')');
                string s = inner.ToString();
                return c.Negate ? "!(" + s + ")" : s;
            }
            else
            {
                string sep = c.Op == CompositeOp.And ? " && " : " || ";
                List<string> parts = new List<string>();
                if (c.Children != null)
                {
                    for (int i = 0; i < c.Children.Count; i++)
                    {
                        Condition child = c.Children[i];
                        string cs = GenCondition(child);
                        if (child.Kind == ConditionKind.Composite &&
                            child.Children != null && child.Children.Count > 1 && !child.Negate)
                            cs = "(" + cs + ")";
                        parts.Add(cs);
                    }
                }
                string joined = string.Join(sep, parts.ToArray());
                return c.Negate ? "!(" + joined + ")" : joined;
            }
        }

        // Like GenCondition, but when the top level is an OR/AND of several terms it puts
        // each term on its own line, so a long domain list reads as a vertical list in the
        // editor. Re-parses fine afterwards (newlines are whitespace to the lexer).
        public static string GenConditionPretty(Condition c)
        {
            if (c == null) return "false";
            if (c.Kind == ConditionKind.Composite && !c.Negate &&
                c.Children != null && c.Children.Count > 1)
            {
                string sep = c.Op == CompositeOp.And ? " &&" : " ||";
                List<string> parts = new List<string>();
                for (int i = 0; i < c.Children.Count; i++)
                {
                    Condition child = c.Children[i];
                    string cs = GenCondition(child);
                    if (child.Kind == ConditionKind.Composite &&
                        child.Children != null && child.Children.Count > 1 && !child.Negate)
                        cs = "(" + cs + ")";
                    parts.Add(cs);
                }
                return string.Join(sep + "\r\n", parts.ToArray());
            }
            return GenCondition(c);
        }

        // Render a .NET string as a JS double-quoted string literal.
        public static string JsString(string s)
        {
            StringBuilder sb = new StringBuilder();
            sb.Append('"');
            if (s != null)
            {
                for (int i = 0; i < s.Length; i++)
                {
                    char ch = s[i];
                    switch (ch)
                    {
                        case '"': sb.Append("\\\""); break;
                        case '\\': sb.Append("\\\\"); break;
                        case '\n': sb.Append("\\n"); break;
                        case '\r': sb.Append("\\r"); break;
                        case '\t': sb.Append("\\t"); break;
                        default:
                            // Other control characters and U+2028/U+2029 (line breaks to
                            // pre-ES2019 engines) are written as \uXXXX escapes.
                            if (ch < ' ' || ch == '\u2028' || ch == '\u2029' || ch == '\u007f')
                                sb.Append("\\u").Append(((int)ch).ToString("x4"));
                            else
                                sb.Append(ch);
                            break;
                    }
                }
            }
            sb.Append('"');
            return sb.ToString();
        }
    }
}
