using System;
using System.Collections.Generic;
using System.Text;
using WpadManager.Core.Model;
using WpadManager.Core.Parser;

namespace WpadManager.Core.Generator
{
    // Deterministically renders a RuleSet back into a valid PAC JavaScript file.
    // Comments round-trip as // lines above each rule; disabled rules are emitted
    // commented-out so they remain visible in the .pac but never fire.
    public static class PacGenerator
    {
        public static string Generate(RuleSet rs)
        {
            Dictionary<int, int> ignore;
            return Generate(rs, out ignore);
        }

        // Same output as Generate, but also reports the 1-based source line on which each
        // rule's statement is emitted (lineToOrder[line] = rule.Order). This lets line-based
        // findings from the security pass be attributed back to the rule the operator sees,
        // so the UI can say "правило N" instead of "строка N".
        public static string Generate(RuleSet rs, out Dictionary<int, int> lineToOrder)
        {
            lineToOrder = new Dictionary<int, int>();

            // Special case: an import that could not find FindProxyForURL is kept whole.
            if (rs.Rules.Count == 0 && rs.Unparsed.Count == 1 &&
                rs.Unparsed[0].Reason == "No FindProxyForURL function")
            {
                return rs.Unparsed[0].RawText;
            }

            // Every piece of stored text below is either JS-escaped (JsString), reduced to a
            // single comment line (LineComment / BlockComment) or checked to be a plain
            // operand (subject / function name). The model can come from a hand-edited
            // .history.json, so nothing in it may be able to change the program's structure.
            StringBuilder sb = new StringBuilder();
            sb.Append("// PAC file generated by WPAD File Manager\n");
            if (!string.IsNullOrEmpty(rs.Name)) sb.Append("// RuleSet: ").Append(LineComment(rs.Name)).Append('\n');
            sb.Append("// Generated: ").Append(Iso.Now()).Append('\n');
            sb.Append('\n');

            // Helper functions / top-level code preserved verbatim before the main function.
            for (int i = 0; i < rs.Unparsed.Count; i++)
            {
                UnparsedBlock ub = rs.Unparsed[i];
                if (ub.Reason != null && ub.Reason.StartsWith("Top-level"))
                {
                    sb.Append("// [preserved from import] ").Append(LineComment(ub.Reason)).Append('\n');
                    sb.Append(ub.RawText).Append('\n').Append('\n');
                }
            }

            sb.Append("function FindProxyForURL(url, host) {\n");

            for (int i = 0; i < rs.Rules.Count; i++)
            {
                Rule r = rs.Rules[i];
                string cond = GenCondition(r.Condition);
                string action = JsString(ActionText.Format(r.Action));
                if (!string.IsNullOrEmpty(r.Comment))
                    sb.Append("    // ").Append(LineComment(r.Comment)).Append('\n');
                // The rule's statement is emitted on the next line; map it to the rule order.
                lineToOrder[CountNewlines(sb) + 1] = r.Order;
                if (r.Enabled)
                    sb.Append("    if (").Append(cond).Append(") return ").Append(action).Append(";\n");
                else
                    sb.Append("    // [disabled] if (").Append(cond).Append(") return ").Append(action).Append(";\n");
            }

            // In-body unparsed blocks (position lost during flattening, but preserved).
            for (int i = 0; i < rs.Unparsed.Count; i++)
            {
                UnparsedBlock ub = rs.Unparsed[i];
                if (ub.Reason == null || !ub.Reason.StartsWith("Top-level"))
                {
                    sb.Append("    /* unparsed (").Append(BlockComment(ub.Reason)).Append("): */ ")
                      .Append(ub.RawText).Append('\n');
                }
            }

            sb.Append("    return ").Append(JsString(ActionText.Format(rs.DefaultAction))).Append(";\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        // Line breaks already written, counted the way the lexer counts them (CRLF once,
        // lone CR / U+2028 / U+2029 once each — verbatim preserved blocks may contain any of
        // these), so the next line to be written is CountNewlines(sb) + 1.
        private static int CountNewlines(StringBuilder sb)
        {
            int n = 0;
            for (int i = 0; i < sb.Length; i++)
            {
                char c = sb[i];
                if (c == '\r' && i + 1 < sb.Length && sb[i + 1] == '\n') continue;
                if (Lexer.IsLineTerminator(c)) n++;
            }
            return n;
        }

        // Text placed after "//": anything JavaScript treats as a line break would end the
        // comment and turn the rest into live code, so flatten it to spaces.
        public static string LineComment(string s)
        {
            if (string.IsNullOrEmpty(s)) return "";
            StringBuilder sb = new StringBuilder(s.Length);
            for (int i = 0; i < s.Length; i++)
                sb.Append(Lexer.IsLineTerminator(s[i]) ? ' ' : s[i]);
            return sb.ToString();
        }

        // Text placed inside /* ... */: must not be able to close the comment early.
        public static string BlockComment(string s)
        {
            if (string.IsNullOrEmpty(s)) return "";
            return s.Replace("*/", "* /");
        }

        // A function name must be a bare identifier; a condition subject must be a single
        // operand (host, url, myIpAddress(), dnsResolve(host), ...). Anything else can only
        // come from a tampered model and is replaced by an inert placeholder — the validator
        // reports it as an error, so such a rule set cannot pass the save gate anyway.
        private static string SafeFn(string fn)
        {
            if (string.IsNullOrEmpty(fn)) return "__invalid_function__";
            for (int i = 0; i < fn.Length; i++)
            {
                char c = fn[i];
                bool ok = (c >= 'a' && c <= 'z') || (c >= 'A' && c <= 'Z') || c == '_' || c == '$' ||
                          (i > 0 && c >= '0' && c <= '9');
                if (!ok) return "__invalid_function__";
            }
            return fn;
        }

        private static string SafeSubject(string subject)
        {
            if (subject == "host" || subject == "url") return subject;   // fast path
            return JsParser.IsSimpleOperand(subject) ? subject : "__invalid_subject__";
        }

        public static string GenCondition(Condition c)
        {
            if (c == null) return "false";
            if (c.Kind == ConditionKind.Single)
            {
                StringBuilder inner = new StringBuilder();
                inner.Append(SafeFn(c.Fn)).Append('(');
                bool first = true;
                if (!string.IsNullOrEmpty(c.Subject))
                {
                    inner.Append(SafeSubject(c.Subject));
                    first = false;
                }
                if (c.Args != null)
                {
                    for (int i = 0; i < c.Args.Count; i++)
                    {
                        if (!first) inner.Append(", ");
                        first = false;
                        inner.Append(JsString(c.Args[i]));
                    }
                }
                inner.Append(')');
                string s = inner.ToString();
                return c.Negate ? "!(" + s + ")" : s;
            }
            else
            {
                string sep = c.Op == CompositeOp.And ? " && " : " || ";
                List<string> parts = new List<string>();
                if (c.Children != null)
                {
                    for (int i = 0; i < c.Children.Count; i++)
                    {
                        Condition child = c.Children[i];
                        string cs = GenCondition(child);
                        if (child.Kind == ConditionKind.Composite &&
                            child.Children != null && child.Children.Count > 1 && !child.Negate)
                            cs = "(" + cs + ")";
                        parts.Add(cs);
                    }
                }
                string joined = string.Join(sep, parts.ToArray());
                return c.Negate ? "!(" + joined + ")" : joined;
            }
        }

        // Like GenCondition, but when the top level is an OR/AND of several terms it puts
        // each term on its own line, so a long domain list reads as a vertical list in the
        // editor. Re-parses fine afterwards (newlines are whitespace to the lexer).
        public static string GenConditionPretty(Condition c)
        {
            if (c == null) return "false";
            if (c.Kind == ConditionKind.Composite && !c.Negate &&
                c.Children != null && c.Children.Count > 1)
            {
                string sep = c.Op == CompositeOp.And ? " &&" : " ||";
                List<string> parts = new List<string>();
                for (int i = 0; i < c.Children.Count; i++)
                {
                    Condition child = c.Children[i];
                    string cs = GenCondition(child);
                    if (child.Kind == ConditionKind.Composite &&
                        child.Children != null && child.Children.Count > 1 && !child.Negate)
                        cs = "(" + cs + ")";
                    parts.Add(cs);
                }
                return string.Join(sep + "\r\n", parts.ToArray());
            }
            return GenCondition(c);
        }

        // Render a .NET string as a JS double-quoted string literal.
        public static string JsString(string s)
        {
            StringBuilder sb = new StringBuilder();
            sb.Append('"');
            if (s != null)
            {
                for (int i = 0; i < s.Length; i++)
                {
                    char ch = s[i];
                    switch (ch)
                    {
                        case '"': sb.Append("\\\""); break;
                        case '\\': sb.Append("\\\\"); break;
                        case '\n': sb.Append("\\n"); break;
                        case '\r': sb.Append("\\r"); break;
                        case '\t': sb.Append("\\t"); break;
                        default:
                            // Other control characters and U+2028/U+2029 (line breaks to
                            // pre-ES2019 engines) are written as \uXXXX escapes.
                            if (ch < ' ' || ch == '\u2028' || ch == '\u2029' || ch == '\u007f')
                                sb.Append("\\u").Append(((int)ch).ToString("x4"));
                            else
                                sb.Append(ch);
                            break;
                    }
                }
            }
            sb.Append('"');
            return sb.ToString();
        }
    }
}
